CREATE DATABASE hotel1;
USE hotel1;
CREATE TABLE IF NOT EXISTS `ht_record`  
(
	`Name` NVARCHAR(100) NULL,
	`CardNo` NVARCHAR(50) NULL,
	`Descriot` NVARCHAR(100) NULL,
	`CtfTp` NVARCHAR(100) NULL,
	`CtfId` NVARCHAR(100) NULL,
	`Gender` NVARCHAR(20) NULL,
	`Birthday` NVARCHAR(50) NULL,
	`Address` NVARCHAR(300) NULL,
	`Zip` NVARCHAR(100) NULL,
	`Dirty` NVARCHAR(100) NULL,
	`District1` NVARCHAR(100) NULL,
	`District2` NVARCHAR(100) NULL,
	`District3` NVARCHAR(100) NULL,
	`District4` NVARCHAR(100) NULL,
	`District5` NVARCHAR(100) NULL,
	`District6` NVARCHAR(100) NULL,
	`FirstNm` NVARCHAR(100) NULL,
	`LastNm` NVARCHAR(100) NULL,
	`Duty` NVARCHAR(100) NULL,
	`Mobile` NVARCHAR(50) NULL,
	`Tel` NVARCHAR(50) NULL,
	`Fax` NVARCHAR(50) NULL,
	`EMail` NVARCHAR(100) NULL,
	`Nation` NVARCHAR(100) NULL,
	`Taste` NVARCHAR(100) NULL,
	`Education` NVARCHAR(2000) NULL,
	`Company` NVARCHAR(2000) NULL,
	`CTel` NVARCHAR(100) NULL,
	`CAddress` NVARCHAR(100) NULL,
	`CZip` NVARCHAR(100) NULL,
	`Family` NVARCHAR(200) NULL,
	`Version` NVARCHAR(200) NULL,
	`id` INT AUTO_INCREMENT  PRIMARY KEY
)
default charset=utf8; 

SELECT * FROM ht_record